// REGISTER ACTIONS
export const REGISTER_EMAIL_CHANGED = 'REGISTER_EMAIL_CHANGED';
export const REGISTER_NAME_CHANGED = 'REGISTER_NAME_CHANGED';
export const REGISTER_PASSWORD_CHANGED = 'REGISTER_PASSWORD_CHANGED';
export const REGISTER_SUBMIT_FORM = 'REGISTER_SUBMIT_FORM';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';


// NOTICIA ACTION
export const NOTICIA_FETCH_ALL = 'NOTICIA_FETCH_ALL';
export const NOTICIA_CREATE = 'NOTICIA_CREATE';
export const NOTICIA_FETCH_ALL_IMAGES = 'NOTICIA_FETCH_ALL_IMAGES';

// CATEGORIA ACTION
export const CATEGORIA_CREATE = 'CATEGORIA_CREATE';
export const CATEGORIA_FETCH_ALL = 'CATEGORIA_FETCH_ALL';
